import { Item as UnitItem } from '../units/unit.interface';

export interface Product {
  id: string;
  product: string;
  unit: string;
}

// Generated by https://quicktype.io

export interface ProductResponse {
  page: number;
  perPage: number;
  totalItems: number;
  totalPages: number;
  items: Item[];
}

export interface Item {
  collectionId: string;
  collectionName: string;
  created: string;
  expand: Expand;
  id: string;
  product: string;
  unit: string;
  updated: string;
}

export interface Expand {
  unit: UnitItem;
}
