export interface Supplier {
  id: string;
  supplier: string;
}

// Generated by https://quicktype.io

export interface SupplierResponse {
  page: number;
  perPage: number;
  totalItems: number;
  totalPages: number;
  items: Item[];
}

export interface Item {
  collectionId: string;
  collectionName: string;
  created: string;
  id: string;
  supplier: string;
  updated: string;
}
