export interface Supplier {
  id: string;
  supplier: string;
}

// Generated by https://quicktype.io
export interface SupplierResponse {
  page: number;
  perPage: number;
  totalItems: number;
  totalPages: number;
  items: Supplier[];
}
