export interface Unit {
  id: string;
  unit: string;
}

// Generated by https://quicktype.io
export interface UnitResponse {
  page: number;
  perPage: number;
  totalItems: number;
  totalPages: number;
  items: Unit[];
}
