export interface Classification {
  id: string;
  classification: string;
}

// Generated by https://quicktype.io

export interface ClassificationResponse {
  page: number;
  perPage: number;
  totalItems: number;
  totalPages: number;
  items: Classification[];
}
